# Generated by Django 5.1.5 on 2025-02-01 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveycategory',
            name='title_en',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='surveycategory',
            name='title_ko',
            field=models.CharField(max_length=500),
        ),
    ]
